# Roles & Responsibilities

## Director

*Michael J. Strambler, Ph.D.*

One of the main responsibilities of the director is to ensure the team has the appropriate funding, personnel, procedures, and physical and social resources to function well. This requires playing an active role in establishing and supervising research projects and acquiring the funding to support them. The director is also responsible for supervising and supporting the professional development of the assistant/associate director, postdoctoral associates/fellows, and research associates. Finally, the director is responsible for ensuring that the team maintains high ethical standards, including the ethical treatment of participants, the protection of sensitive data, and a respectful, open, and professional team culture. When problems arise in team culture, ethics, or research design, the director is responsible for addressing them and getting the team back on track.

## Assistant Director

A distinguishing characteristic of the Assistant Director is that they are a key thought partner on the team's mission and focus. The Assistant Director is expected to make substantive contributions to planning around the types of projects we take on, ensuring that they are consistent with our mission and philosophy. Another key responsibility involves co-directing and managing projects with the Director. This includes developing work plans for projects, pressing the team regarding progress and deadlines, establishing and maintaining IRB protocols, and planning for grant proposals. Supervisory responsibilities include hiring and supervising research assistants for the team.

## Research Associate

Research Associates have advanced research, data analytic, evaluation, and/or project management skills. The Research Associate applies these skills to specific projects in collaboration with the Director or Assistant Director. The responsibilities of the Research Associate are project-specific, but may involve data analysis, measurement development, report writing, project management, and research design. Research Associates are expected to stay current on new developments in their skill set.

## Postdoctoral Fellows and Associates

Although postdocs are trainees, they are also considered key colleagues of the CWER team. Postdocs have two main responsibilities: (1) to clarify and move towards their training goals with the support of the director, and (2) to contribute to assigned research projects. For the first responsibility, postdocs should take active steps to seek advice and professional experiences from the director and other appropriate mentors. They should also participate in relevant training seminars in grant writing, professional development, and research methods. Regarding project contributions, postdocs are expected to bring new skills to the team that will help improve the work. The director will assist postdocs in finding a balance between working on CWER projects and establishing their professional independence.

## Research Assistants

Research assistants (RAs) can be paid or volunteer team members who are brought on to support the research of specific projects. RA responsibilities are project-specific and can include data management and processing, data collection, data analysis (usually less advanced techniques), literature searches and reviews, documentation, meeting facilitation, focus groups, interviews, and report writing.