# Being a Team Member

## Human Research Training

Every member must complete and stay current with the appropriate human research trainings, including HIPAA, CITI basic training, and any other related Yale trainings. You can find this information [here](https://your.yale.edu/research-support/human-research/education-and-training/human-research-training).

## Data Security and Privacy

Collecting data from someone is like collecting a part of their person, and we have an ethical obligation to treat this information with the utmost care. Accordingly, we take data security very seriously. Data of moderate or high risk should be handled with the procedures described below (see Yale's definitions of risk [here](https://cybersecurity.yale.edu/know-your-risk#:~:text=Yale%20uses%20three%20risk%20classifications%20for%20data,on%20risk%20using%20Minimum%20Security%20Standards%20(MSS).)).

- If you are not sure whether data are moderate or high-risk, ask either Mike or Joanna before you do anything — or just treat the data as high risk. It is always better to be more cautious when in doubt. Check the IRB protocol and data sharing agreements on issues regarding data protection and sharing.

- Moderate and high-risk data can **only** be saved in the following places: (1) the Yale server (Storage @ Yale); (2) Yale Secure Box (this is different from "regular" Yale Box); (3) Yale-managed Microsoft OneDrive or SharePoint; (4) temporarily on a Yale-managed encrypted hard drive; or (5) temporarily on a Yale-issued IronKey flash drive.

- Saving data on Yale encrypted hard drives or IronKey flash drives should **only** be done when you do not have access to the internet, or you need to transfer data from one location to another. In such cases, immediately transfer data to the server or Secure Box when you have internet access.

- **Never** electronically transmit data with personally identifiable information through any means other than Yale's Secure File Transfer (or another secure FTP process when partners are transmitting files). Although Yale has a Microsoft Outlook email encryption feature, never use this for transmitting moderate or high-risk data — it is too easy to make a mistake.

- Yale issues [free high-security flash drives](https://yale.service-now.com/it?id=service_offering&sys_id=87688dcd6fbb31007ee2abcf9f3ee427) upon request. It is a good idea to have one on hand in case you need to temporarily store sensitive data. This is secure enough to store high-risk data, but only for transporting data from one secure system to another.

## Open Science & Research Integrity

In line with our philosophy of truthfulness, we aim to practice open science. The term *open science* encompasses many concepts, including sharing data and materials, using best practices in research design and statistics, and promoting research reproducibility and replicability. The way we like to think of these practices is engaging in *research integrity* — research that is transparent and credible.

Although we do not always have the option to share data given partners' privacy concerns, we make every effort to produce research that is *reproducible*, meaning that someone else with the same access to our data could produce identical findings using the study information we provide. This is also useful for other researchers to examine *replicability*, or the production of similar findings using a separate dataset.

Some of the practices we aim to use include:

- Sharing as many study materials as possible (see OSF in the [Tools](../tools/tools-overview.qmd) chapter)
- Clearly documenting and sharing analysis code when appropriate
- Using methods appropriate for communicating meaningful, interpretable, and accurate findings
- Establishing data analysis plans *prior* to data collection to:
  - Ensure we collect the proper data and have an adequate sample size to address the research questions
  - Help avoid biased practices like [HARKing](https://journals.sagepub.com/doi/10.1207/s15327957pspr0203_4) (hypothesizing after results are known) and [*p*-hacking](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002106&) (intentionally or unintentionally tweaking analyses to reach statistical significance)